### ISSUE TITLE
How to reproduce the experiments in build?

### ISSUE THREAD

**Issue by wypppp** [nicolaskagami/capest#1]
Hi,

I was wondering if you could share a detailed guide to reproducing the experiment.I can configure the switch, but it shows this figure, I don't know what the problem is.
![image](https://user-images.githubusercontent.com/47921667/117229068-df2dcb80-ae4c-11eb-932f-e5d8822a2202.png)

Thanks!

**Comment by nicolaskagami** [comment]
Hello

It seems you're running the ms_mininet_test.py and having problems running the capest_visualizer and/or cplayer.
Did you compile the cplayer and capest_visualizer? There are very simple Makefiles for each of them in their respective folders.

I'm sorry I can't take the time to make a detailed guide.

Good luck!

**Comment by wypppp** [comment]
> Hello
> 
> It seems you're running the ms_mininet_test.py and having problems running the capest_visualizer and/or cplayer.
> Did you compile the cplayer and capest_visualizer? There are very simple Makefiles for each of them in their respective folders.
> 
> I'm sorry I can't take the time to make a detailed guide.
> 
> Good luck!

Thanks for your reply!I've compiled all the capest_visualizer and cplayer,and copied capest_visualizer and sink to build. but I'm still having the same problem.
I have one more question to ask you, how to use sink and capest_visualizer? I can't use them in terminal, and what is the hostname?
This is my first time to learn p4, many questions are really elementary, please understand.
Thank you!

**Comment by nicolaskagami** [comment]
1.  "what is the hostname?": The hostname is a label do identify the host (such as your computer, phone, etc). In the case of mininet, we have a few emulated hosts: h1, h2, h3, etc.

2.  "how to use sink and capest_visualizer?": In theory the ms_mininet_test.py runs both of these for you, as can be seen in `subprocess.Popen('sudo ../sink/sink s4-eth2 127.0.0.1 6666 &',shell=True)` and `capest = subprocess.Popen('sudo script -c "../sink/capest_visualizer 6666" -f ./.capestd &',shell=True)`. In this case, the sink needs to be run in an environment where the interface s4-eth2 is known. What happens if you try to run these commands (`sudo ...`)?

I would say this is a somewhat advanced project for a P4 beginner to undertake. It would be good to learn a bit about Mininet, P4 and computer networks in general.
